version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_vetoexpress
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: VetoExpress3
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_vetoexpress
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8088:80"
    depends_on:
      - mysql

  api:
    build: .
    container_name: express_vetoexpress
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=VetoExpress3
      - DB_PORT=3306
      - JWT_SECRET=HelloWorld!
      - JWT_SECRETisValidate=HelloWorld!isValidate
      - EMAIL_USER=larbibenyakhou.info@gmail.com
      - EMAIL_PASS=pwji maxd grmy kpvs
    depends_on:
      - mysql
    volumes:
      - .:/app
    working_dir: /app
    command: npm start

volumes:
  mysql_data:
    driver: local
