version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_vetoexpress
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: VetoExpress3
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_vetoexpress
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8088:80"
    depends_on:
      - mysql

  api:
    build: .
    container_name: express_vetoexpress
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm start

volumes:
  mysql_data:
    driver: local
